### ISSUE TITLE
Pedigree not drawn where female has children with her nephew?

### ISSUE THREAD

**Issue by grant32** [piratical/Madeline_2.0_PDE#32]
Hi Ed, I've attached a sample input file that isn't generating a drawing. Looks like person 5 has children (5,10) with her nephew (9). There is nothing in the log to indicate an error (I used the flag --debug). Thanks in advance for taking a look. I'm using Madeline2 on Windows.

[test.txt](https://github.com/piratical/Madeline_2.0_PDE/files/127457/test.txt)

**Comment by piratical** [comment]
Hi, Grant32,

Are you sure you've attached the correct data file? The file you attached seems to draw correctly and does not have any consanguinous relationship as you describe. I am not seeing any aunt married to a nephew.

**Comment by grant32** [comment]
Ed, My apologies for the error. I downloaded the latest source and the drawing is now created (it caused a core dump previously). However, I did notice that there is no longer any messages to indicate disconnected individuals. I used to see something like: "Warning: Individual 100610 is Unconnected.", but that information is no longer output (I tried with the --debug option also). Do you still capture this information? Many thanks for your time.

**Comment by piratical** [comment]
Hi, Grant32,

Thank you for pointing out the regression where unconnected individuals were not being reported. This has now been fixed in the latest commit, ee5d1dfbb930f8fbfb521aae44f0d1c9369292b9.

In addition, a new test data file, unconnected_001.data, has been added to the (also new) testing_framework.

So I am going to close out this issue as resolved at this time.  — Ed
