### ISSUE TITLE
Force male partner to always render on left in relationship line

### ISSUE THREAD

**Issue by huyhong** [piratical/Madeline_2.0_PDE#39]
Per the NSGC recommendation on the [Standardized Human Pedigree Nomenclature](http://geneticcounselingtoolkit.com/cases/pedigree/Bennett%20JGC%202008%20-%20Standardized%20Human%20Pedigree%20Nomenclature%20-%20Update%20and%20Assessment%20of%20the%20Recommendations%20of%20the%20National%20Society%20of%20Genetic%20Counselors.pdf):
> If possible, male partner should be to left of female partner on relationship line

Having issues finding out how to force drawings to always render the male partner on the left. If you have any pointers where to look in the code, would much appreciate :).

Example data:
```
FamilyId
IndividualId
Gender
Father
Mother
Deceased
Proband
DOB
MZTwin
DZTwin
Sampled

Test U0p100 M .      .      Y . .          . . .
Test U0p101 F .      .      Y . .          . . .
Test U0m100 M .      .      Y . .          . . .
Test U0m101 F .      .      Y . .          . . .
Test U00200 M U0p100 U0p101 Y . .          . . .
Test U00201 F U0m100 U0m101 Y . .          . . .
Test U00102 M .      .      . . .          . . .
Test U00107 F U00200 U00201 . Y .          . . .
Test U00108 F U00102 U00107 . . .          . . .
Test U00109 F U00102 U00107 . . .          . . .
```

Resulting drawing from example data above:
<img width="1004" alt="screen shot 2016-11-21 at 3 19 02 pm" src="https://cloud.githubusercontent.com/assets/33226/20504752/069a316a-affe-11e6-95c9-e55a3d5bb8c2.png">

Example issues:
- Female Proband (`U00107`) is drawn on left (I suspect this is because the ancestry relationships exist for this individual, if Proband was Male, he would appear on the left)
- Proband parents are always drawn with Female/Mother (`U00201`) on left

**Comment by piratical** [comment]
Hi, Huyhong,

You are right about the Pedigree Standardization Taskforce recommendation that the male partner always be rendered on the left. When we wrote Madeline 2.0 PDE, we were aware of Bennett et al.'s paper, but we felt certain recommendations of the Task Force were very arbitrary and did not enhance pedigree readability. Having the male always on the left is one of those arbitrary "standards" that we did not give much weight to. In the example that you provided, the nuclear family that begins with U0m100 & U0m101 is rendered first (in this case because the ID numbers sort at the beginning of the sorted list of all individual IDs) and therefore offspring U00201 is drawn on the left.  U00107 is also drawn on the left because U00107 is part of the U0m100 & U0m101 descent tree, while U00102 is a married-in "founder" with no ancestors shown. The rule in Madeline 2.0 is to draw the direct descendants in a descent tree first, and then their married-in spouses after them on the right, with absolutely no regard to gender.  In this way, Madeline is a bit gender "agnostic".  If I have time, I'll look for the place in the code where this could be modified. If I do modify it, most likely I would implement a new switch to force "male on left" or "female on left", while the default would probably remain as it currently is ...
