### ISSUE TITLE
Create tag/release?

### ISSUE THREAD

**Issue by holtgrewe** [piratical/Madeline_2.0_PDE#43]
Would it be possible to create a tag/release here on Github?

I would like to include Madeline into [Bioconda](http://bioconda.github.io/).

**Comment by piratical** [comment]
Hi, Manuel,

Including Madeline in Bioconda sounds fine with me.

I'm not quite clear what your question is. Do you need me to do something?

Best Wishes -- Ed

**Comment by holtgrewe** [comment]
Hi Ed,

it would be nice if there was a Git tag with the current version. This way, I can refer to this tag instead of a commit in the Bioconda package. Future update releases would then of course require new tags.

Cheers,
Manuel

**Comment by nieder** [comment]
I'm also trying to package madeline for macOS ([fink package manager](https://www.finkproject.org/)). Not having a tag/release makes it difficult for any distribution to package madeline.

Looking at the source, MADELINE_VERSION was bumped to 2.1 with commit 36aff0368848a8125e95da2621dd748d485e99a0.
Tagging the previous commit a92c1f8b8ff2223a5f42c96f12e7232dcafc544e or perhaps the one before it c9d7f9ab1586e0e2d09708d2cc45df6336a2f9ff since it didn't introduce a new class as v2.0 (or some other identifying version) would automatically create zip and tar.gz files of the repo at that point to simplify downloading.
There have been ~180 commits to the repo since that commit. Maybe something there could also be tagged as v2.1 to mark all the changes in the past 8 years.

**Comment by piratical** [comment]
Hi, Nieder,

I just created this tagged release:

https://github.com/piratical/Madeline_2.0_PDE/releases/tag/v.2.1.1

I hope this satisfies your needs. If you need anything else, please let me
know.

Best Wishes -- Ed

**Comment by nieder** [comment]
Thank you. Added to Fink (macOS package manager):
https://pdb.finkproject.org/pdb/package.php/madeline2
